---
- name: Account creation
  hosts: all
  tasks:

  ######################### Default groups for all linux users #########################
    - name: Ensure group {{ item.name }} exists
      become: yes
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
        # gid: "{{ item.gid }}"
      loop:
        - { name: 'admin' } # Create group titled admin and with gid 1030
        - { name: 'qa' }
        - { name: 'dev' }
      when: "'linux' in group_names"

  ######################### Master groups for all linux users #########################
    - name: Ensure group {{ item.name }} exists
      become: yes
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
        # gid: "{{ item.gid }}"
      loop:
        - { name: 'admin-master' } # Create group titled admin and with gid 1030
        - { name: 'qa-master' }
        - { name: 'dev-master' }
      when: 
        - "'master' in group_names"
        - "'linux' in group_names"

  ######################### Nodes groups for all linux users #########################
    - name: Ensure group {{ item.name }} exists
      become: yes
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
        # gid: "{{ item.gid }}"
      loop:
        - { name: 'admin-nodes' } # Create group titled admin and with gid 1030
        - { name: 'qa-nodes' }
        - { name: 'dev-nodes' }
      when: 
        - "'nodes' in group_names"
        - "'linux' in group_names"

  ######################### Remove Groups #########################
    - name: Remove group {{ item.name }}
      become: yes
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: absent
      loop:
        - { name: ''}
      ignore_errors: True
      when: "'linux' in group_names"