---
- name: Account Management
  hosts: all
  tasks:

  ######################### Default users for all linux users #########################
    - name: Add Internal user {{ item.name }} with a bash shell, appending the group {{ item.groups }}
      become: yes
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        password: "{{ item.password | password_hash('sha512')}}"
        update_password: "on_create"
        # uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        append: yes
      loop:
        - { name: 'storm', groups: 'admin,dev', password: 'Admin123456' } # Add a user with username storm part of the admin and dev groups with uid 1005
        - { name: 'mattm', groups: 'admin,dev', password: 'Admin123456' }
      register: accounts_def
      notify: force change password default
      when: "'linux' in group_names"

    - debug:
        var: accounts_def.results

  ######################### Master Users #########################
    - name: Add Internal user {{ item.name }} with a bash shell, appending the group {{ item.groups }}
      become: yes
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        password: "{{ item.password | password_hash('sha512')}}"
        update_password: "on_create"
        # uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        append: yes
      loop:
        - { name: 'master-user-01', groups: 'admin,dev', password: 'Admin123456' }
        - { name: 'master-user-02', groups: 'admin,dev', password: 'Admin123456' }
      register: accounts_master
      notify: force change password master
      when: 
        - "'master' in group_names"
        - "'linux' in group_names"

  ######################### Nodes Users #########################
    - name: Add Internal user {{ item.name }} with a bash shell, appending the group {{ item.groups }}
      become: yes
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        password: "{{ item.password | password_hash('sha512')}}"
        update_password: "on_create"
        # uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        append: yes
      loop:
        - { name: 'nodes-user-01', groups: 'admin,dev', password: 'Admin123456' }
        - { name: 'nodes-user-02', groups: 'admin,dev', password: 'Admin123456' }
      register: accounts_nodes
      notify: force change password nodes
      when: 
        - "'nodes' in group_names"
        - "'linux' in group_names"

  ######################### Remove Users #########################
    - name: Remove User {{ item.name }}
      become: yes
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      loop:
        - { name: '' }
      ignore_errors: True
      when: "'linux' in group_names" 


    ######################### Handlers #########################
  handlers:
    - name: force change password default
      become: yes
      shell: |
        sudo chage -d 0 {{ item.name }}
      when: item.changed
      loop: "{{ accounts_def.results }}"

    - name: force change password master
      become: yes
      shell: |
        sudo chage -d 0 {{ item.name }}
      when: item.changed
      loop: "{{ accounts_master.results }}"

    - name: force change password nodes
      become: yes
      shell: |
        sudo chage -d 0 {{ item.name }}
      when: item.changed
      loop: "{{ accounts_nodes.results }}"
