---
- name: Account creation
  hosts: all
  tasks:
    - name: Add the user {{ item.name }} with a bash shell, appending the group {{ item.groups }}
      become: yes
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        uid: 1002
        groups: "{{ item.groups }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        append: yes
      loop:
        - { name: 'storm', groups: 'admin,dev' }
        - { name: 'stormey', groups: 'admin,qa' }