- hosts: all
  tasks:
  - name: display informations
    debug:
      msg: "echo OS: {{ ansible_facts['os_family'] }} , OS Distribution: {{ ansible_facts['distribution'] }},  HostName: {{ ansible_facts['hostname'] }} , Groups: {{ group_names }}"

  - name: Emulate long process
    pause:
      seconds: 10

  - name: Include secret vars
    include_vars: 
      file: "{{ playbook_dir }}/secrets/test.yml"
      name: secrets

  - name: display secrets
    debug: 
      msg: 
        - "My root password is: {{ secrets.root_pass }}"
        - "My admin password is: {{ secrets.admin_pass }}"
        - "My user password is: {{ secrets.user_pass }}"