- hosts: m2
  become: yes
  tasks:
  - name: Create a directory named Ubuntu if it does not exist
    ansible.builtin.file:
      path: /home/ubuntu/ubuntu2
      state: directory
      mode: '0755'
  - name: This command will change the working directory to ubuntu2/
    ansible.builtin.shell:
      cmd: echo "I am number two" > machine2.txt
      chdir: /home/ubuntu/ubuntu2/