- hosts: m1
  become: yes
  tasks:
  - name: Create a directory named Ubuntu if it does not exist
    ansible.builtin.file:
      path: /home/ubuntu/ubuntu1
      state: directory
      mode: '0755'
  - name: This command will change the working directory to ubuntu1/
    ansible.builtin.shell:
      cmd: echo "I am number one" > machine1.txt
      chdir: /home/ubuntu/ubuntu1/