---
- hosts: all
  tasks:
  - name: display informations
    debug:
      msg: "echo OS: {{ ansible_facts['os_family'] }} , OS Distribution: {{ ansible_facts['os_distribution'] }},  HostName: {{ ansible_facts['hostname'] }} , Groups: {{ group_names }}"
