---
- name: Account creation
  hosts: all
  tasks:
    - name: Ensure group {{ item.name }} exists with correct gid {{ item.gid }}
      become: yes
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
        gid: "{{ item.gid }}"
      loop:
        - { name: 'admin', gid: 1030 }
        - { name: 'qa', gid: 1031 }
        - { name: 'dev', gid: 1032 }
        - { name: 'mf', gid: 1033 }