- hosts: master
  tasks:
  - name: display informations on master node
    debug:
      msg: "echo OS: {{ ansible_facts['os_family'] }} , OS Distribution: {{ ansible_facts['distribution'] }},  HostName: {{ ansible_facts['hostname'] }} , Groups: {{ group_names }}"
      
  - name: Kubectl Installation | Binaries and testing
    shell: |
      touch config
      cat <<EOF > config
      {{ kubeconfigfile }}
      EOF
      export KUBECONFIG=config
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.28.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      ./kubectl get nodes
    register: k8s_status

  - debug:
      var: k8s_status.stdout_lines

  - name: Get nginx pod
    shell: |
      touch config
      cat <<EOF > config
      {{ kubeconfigfile }}
      EOF
      export KUBECONFIG=config
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.28.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl    
      ./kubectl get pods -n nginx | grep nginx-
    register: pod_status
  
  - debug:
      var: pod_status.stdout_lines
      

  - name: Restart nginx pod | Get the pod name
    shell: |
      touch config
      cat <<EOF > config
      {{ kubeconfigfile }}
      EOF
      export KUBECONFIG=config
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.28.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      ./kubectl get po -n nginx | grep nginx- | awk '{print $1}'
    register: pod_name

  - debug:
      var: pod_name.stdout

  - name: Restart nginx pod | restart the pod
    shell: |
      touch config
      cat <<EOF > config
      {{ kubeconfigfile }}
      EOF
      export KUBECONFIG=config
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.28.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      ./kubectl delete po {{ pod_name.stdout }} -n nginx 

  - name: Emulate long process
    pause:
      seconds: 10
      
  - name: Restart nginx pod | Get the pod status
    shell: |
      touch config
      cat <<EOF > config
      {{ kubeconfigfile }}
      EOF
      export KUBECONFIG=config
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.28.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      ./kubectl get pods -n nginx | grep nginx-
    register: pod_state

  - debug:
      var: pod_state.stdout