- hosts: lab1
  tasks:
  - name: display informations on master node
    debug:
      msg: "echo OS: {{ ansible_facts['os_family'] }} , OS Distribution: {{ ansible_facts['distribution'] }},  HostName: {{ ansible_facts['hostname'] }} , Groups: {{ group_names }}"

  - name: Get nginx pod
    shell: kubectl get pods | grep nginx-
    register: pod_status
  
  - debug:
      var: pod_status.stdout_lines