- hosts: master
  tasks:

  - name: Include secret vars
    include_vars: 
      file: "../{{ playbook_dir }}/secrets/test.yml"
      name: secrets

  - name: display informations on master node
    debug:
      msg: "echo VAR: {{ secrets.kubeconfighome }}, OS: {{ ansible_facts['os_family'] }} , OS Distribution: {{ ansible_facts['distribution'] }},  HostName: {{ ansible_facts['hostname'] }} , Groups: {{ group_names }}"

  - name: Kubectl Installation | Kubeconfig file
    shell: |
      cat <<EOF > config
      {{ secrets.kubeconfighome }}
      EOF
      cat config
    register: kube_log

  - debug:
      var: kube_log.stdout_lines

  - name: Kubectl Installation | Binaries and testing
    shell: |
      cat <<EOF > config
      {{ secrets.kubeconfighome }}
      EOF
      export KUBECONFIG=config
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.28.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      ./kubectl get nodes
    register: k8s_status

  - debug:
      var: k8s_status.stdout_lines
      
