- hosts: master
  tasks:
  - name: display informations on master node
    debug:
      msg: "echo VAR: {{ kubeconfigfile }}, OS: {{ ansible_facts['os_family'] }} , OS Distribution: {{ ansible_facts['distribution'] }},  HostName: {{ ansible_facts['hostname'] }} , Groups: {{ group_names }}"

  - name: Kubectl Installation | Kubeconfig file 1
    shell: |
      mkdir .kube
      touch .kube/config

  - name: Kubectl Installation | check folder kube
    shell: |
      ls .kube
    register: kube_file

  - name: Kubectl Installation | Kubeconfig file 2
    copy:
      dest: ./kube/config
      content: |
        {{ kubeconfigfile }}

  - name: Kubectl Installation | Check Kubeconfig file
    shell: |
      cat .kube/config
    register: kube_log

  - debug:
      var: kube_log.stdout_lines
      
