- hosts: master
  tasks:
  - name: display informations on master node
    debug:
      msg: "echo VAR: {{ kubeconfigfile }}, OS: {{ ansible_facts['os_family'] }} , OS Distribution: {{ ansible_facts['distribution'] }},  HostName: {{ ansible_facts['hostname'] }} , Groups: {{ group_names }}"

  - name: Kubectl Installation | Kubeconfig file
    shell: |
      mkdir .kube
      touch .kube/config
      cat <<EOF > ./kube/config
      {{ kubeconfigfile }}
      EOF
      cat .kube/config
    register: kube_log

  - debug:
      var: kube_log.stdout_lines
      
